config/routes.rb
Rails.application.routes.draw do

    devise_for :users
    scope "/admin" do
      resources :users
    end
  resources :roles

    root to: 'areas#index'

    get 'unstructured_data/ahp'
    post 'unstructured_data/ahpcalculate'
    resources :unstructured_data

    get 'ahp/criteria'
    post 'ahp/calculate'

    resources :criteria do
        resources :subcriteria
    end

    get  'plants/:id/detail' => 'plants#detail', as: :plant_detail
    post 'plants/:id/detail' => 'plants#savedetail', as: :plant_save_detail
    resources :plants

    get 'areas/:id/calculate' => 'areas#calculate', as: :area_calculate
    resources :areas

end

app/controllers/unstructured_data_controller.rb
class UnstructuredDataController < ApplicationController
  before_action :set_unstructured_datum, only: [:show, :edit, :update, :destroy]

  # GET /unstructured_data
  # GET /unstructured_data.json
  def index
      @unstructured_data = UnstructuredDatum.includes(:subcriterium).all
  end

  # GET /unstructured_data/1
  # GET /unstructured_data/1.json
  def show
  end

  # GET /unstructured_data/new
  def new
      @subcriteria = Subcriterium.where('tipe', false)
    @unstructured_datum = UnstructuredDatum.new
  end

  # GET /unstructured_data/1/edit
  def edit
  end

  # POST /unstructured_data
  # POST /unstructured_data.json
  def create
    @unstructured_datum = UnstructuredDatum.new(unstructured_datum_params)

    respond_to do |format|
      if @unstructured_datum.save
        format.html { redirect_to @unstructured_datum, notice: 'Unstructured datum was successfully created.' }
        format.json { render :show, status: :created, location: @unstructured_datum }
      else
        format.html { render :new }
        format.json { render json: @unstructured_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unstructured_data/1
  # PATCH/PUT /unstructured_data/1.json
  def update
    respond_to do |format|
      if @unstructured_datum.update(unstructured_datum_params)
        format.html { redirect_to @unstructured_datum, notice: 'Unstructured datum was successfully updated.' }
        format.json { render :show, status: :ok, location: @unstructured_datum }
      else
        format.html { render :edit }
        format.json { render json: @unstructured_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unstructured_data/1
  # DELETE /unstructured_data/1.json
  def destroy
    @unstructured_datum.destroy
    respond_to do |format|
      format.html { redirect_to unstructured_data_url, notice: 'Unstructured datum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
    
    def ahp
        @subcriteria = Subcriterium.where(tipe: false).includes(:unstructured_data)
    end
    
    def ahpcalculate
        # Mulai Hitung AHP untuk setiap sub sub
        # Khusus topografi tidak memiliki sub, jadi tidak dihitung
        @subcriteria = Subcriterium.where(tipe: false).includes(:unstructured_data)
        @UD = {}
        @subcriteria.each do |sub|
            ud         = sub.unstructured_data
            panjangud  = ud.length
            
            # Mulai Hitung AHP untuk setiap unstructured_data(ud)
            # Simpan semua data AHP ud khusus id ini ke dalam variabel @subcriteria
            @UD[sub.id] = {}
            @UD[sub.id][:sum] = {}
            @UD[sub.id][:sumpv] = {}
            @UD[sub.id][:sqrt3] = {}
            @UD[sub.id][:bobot] = {}
            @UD[sub.id][:nilai] = {}
            ud.each_with_index do |baris, index|
                # Jika akar pangkat 3 ud kosong, ubah jadi 1
                @UD[sub.id][:sqrt3][index] = 1 if @UD[sub.id][:sqrt3][index] == nil;
                ud.each_with_index do |kolom, idx|
                    # Hitung nilai2 matrix nya berdasarkan input
                    if index == idx
                        @UD[sub.id][:nilai]["#{index}#{idx}"] = 1
                    elsif index < idx
                        @UD[sub.id][:nilai]["#{index}#{idx}"] = params[:ud][baris.id.to_s][kolom.id.to_s].to_f
                    else
                        @UD[sub.id][:nilai]["#{index}#{idx}"] = 1/params[:ud][kolom.id.to_s][baris.id.to_s].to_f
                    end
                    # Jumlahkan 1 kolom menurun
                    @UD[sub.id][:sum][idx] = @UD[sub.id][:sum][idx].to_f + @UD[sub.id][:nilai]["#{index}#{idx}"].to_f;
                    # Hitung produknya kemudian ambil akar pangkat 3 nya
                    @UD[sub.id][:sqrt3][index] = @UD[sub.id][:sqrt3][index].to_f * @UD[sub.id][:nilai]["#{index}#{idx}"].to_f
                    if idx == ud.length-1 then 
                        @UD[sub.id][:sqrt3][index] = @UD[sub.id][:sqrt3][index]**(1.to_f/(ud.length).to_f).to_f 
                    end
                    # Jumlahkan secara menurun hasil dari sqrt
                end
            end
            # hitung bobot per sub sub
            @UD[sub.id][:sumSqrt3] = 0.0
            ud.length.times { |i| @UD[sub.id][:sumSqrt3] = (@UD[sub.id][:sumSqrt3] + @UD[sub.id][:sqrt3][i].to_f).to_f }
            @UD[sub.id][:lambda]   = 0.0
            @UD[sub.id][:sumbobot]   = 0.0
            for i in 0..ud.length-1
                @UD[sub.id][:bobot][i] = (@UD[sub.id][:sqrt3][i].to_f/@UD[sub.id][:sumSqrt3].to_f)
                @UD[sub.id][:sumbobot] = (@UD[sub.id][:sumbobot] + @UD[sub.id][:bobot][i].to_f).to_f
                data = UnstructuredDatum.find(ud[i].id)
                data.ahp = @UD[sub.id][:bobot][i]
                data.save
                @UD[sub.id][:sumpv][i]= (@UD[sub.id][:sum][i]*@UD[sub.id][:bobot][i])
                @UD[sub.id][:lambda]  = (@UD[sub.id][:lambda] + @UD[sub.id][:sumpv][i])
            end
        end
#            render json: @UD.to_json
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unstructured_datum
      @unstructured_datum = UnstructuredDatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unstructured_datum_params
      params.require(:unstructured_datum).permit(:name, :subcriterium_id)
    end
end

app/helpers/unstructured_data_helper.rb
module UnstructuredDataHelper
end

app/views/unstructured_data/_form.html.erb
<%= form_for(@unstructured_datum) do |f| %>
  <% if @unstructured_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unstructured_datum.errors.count, "error") %> prohibited this unstructured_datum from being saved:</h2>

      <ul>
      <% @unstructured_datum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Nama' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :subcriterium_id, 'Kriteria' %><br>
      <%= collection_select(:unstructured_datum, :subcriterium_id, Subcriterium.where(tipe: false), :id, :name) %>
    <%#= f.text_field :subcriterium_id %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-block btn-primary' %>
  </div>
<% end %>

app/views/unstructured_data/ahp.html.erb
<h2>Perhitungan AHP Unstructured Data</h2>
<%= form_tag(unstructured_data_ahpcalculate_path) do |f|  %>
    <% @subcriteria.each_with_index do |subcriteria, subindex| %>
    <hr>
    <table class="table table-condensed table-bordered table-striped">
        <thead>
            <tr>
                <th>Data</th>
                <% subcriteria.unstructured_data.each do |ud| %>
                <th><%= ud.name %></th>
                <% end %>
            </tr>
        </thead>
        <tbody>
            <% subcriteria.unstructured_data.each_with_index do |baris, index| %>
            <tr>
                <td><%= baris.name %></td>
                <% subcriteria.unstructured_data.each_with_index do |kolom, idx| %>
                    <% if index == idx %>
                    <td>1</td>
                    <% elsif index < idx %>
                    <td><input type="text" style="width: 50px" name="ud[<%=baris.id%>][<%=kolom.id%>]" value="2"></td>
                    <% else %>
                    <td></td>
                    <% end %>
                <% end %>
            </tr>
            <% end %>
        </tbody>
    </table>
    <% end %>
    <button class="btn btn-block btn-primary">Hitung Bobot</button>
<% end %>

app/views/unstructured_data/ahpcalculate.html.erb
<h2>Perhitungan AHP Data Tak Terstruktur</h2>
<% @subcriteria.each do |sub| %>
    <% if sub.unstructured_data.length > 0 %>
    <h3>Perhitungan AHP untuk "<%= sub.name %>"</h3>
    <table class="table table-condensed table-bordered table-striped">
        <thead>
        <tr>
            <th>Data</th>
            <% sub.unstructured_data.each do |ud| %>
            <th><%= ud.name %></th>
            <% end %>
            <th>Akar Pk3</th>
            <th>Bobot</th>
        </tr>
        </thead>
        <tbody>
            <% sub.unstructured_data.each_with_index do |baris, index| %>
                <tr>
                    <td><%= baris.name %></td>
                    <% sub.unstructured_data.each_with_index do |kolom, idx| %>
                        <% if baris.id == kolom.id %>
                        <td>1</td>
                        <% else %>
                        <td><%= @UD[sub.id][:nilai]["#{index}#{idx}"] %></td>
                        <% end %>
                    <% end %>
                    <td><%= @UD[sub.id][:sqrt3][index] %></td>
                    <td><%= @UD[sub.id][:bobot][index] %></td>
                </tr>
            <% end %>
        </tbody>
        <tfooter>
        <tr>
            <th>Sum</th>
            <% for kolom in 0..sub.unstructured_data.length-1 %>
            <td><%= @UD[sub.id][:sum][kolom] %></td>
            <% end %>
            <td><%= @UD[sub.id][:sumSqrt3] %></td>
            <td><%= @UD[sub.id][:sumbobot] %></td>
        </tr>
        <tr>
            <th>Sum*pv</th>
            <% for kolom in 0..sub.unstructured_data.length-1 %>
                <td><%= @UD[sub.id][:sum][kolom]*@UD[sub.id][:bobot][kolom] %></td>
            <% end %>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <th>Lamdamax</th>
            <td><%= @lambda %></td>
        </tr>
        <tr>
            <th>CI</th>
            <td><%= @ci %></td>
        </tr>
        <tr>
            <th>CR</th>
            <td><%= @cr %></td>
        </tr>
    </tfooter>
    </table>
    <% end %>
<% end %>
<a href="" class="btn btn-primary btn-block">Hitung SubCriteria &raquo;</a>

app/views/unstructured_data/edit.html.erb
<h1>Edit Data Tak Terstruktur</h1>

<%= render 'form' %>

<%= link_to 'Lihat', @unstructured_datum %> |
<%= link_to 'Kembali', unstructured_data_path %>

app/views/unstructured_data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Daftar Data Tak Terstruktur</h1>
<% if current_user.role.id == 3 %>
<a href="<%= unstructured_data_ahp_path %>" class="btn btn-blockk btn-primary">Hitung AHP</a>
<% end %>
<table class="table table-condensed table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>SubKriteria</th>
            <% if current_user.role.id != 3 %>
            <th colspan="3">Aksi</th>
            <% end %>
        </tr>
    </thead>

    <tbody>
        <% @unstructured_data.each do |unstructured_datum| %>
        <tr>
            <td><%= unstructured_datum.name %></td>
            <td><%= unstructured_datum.subcriterium.name %></td>
            <% if current_user.role.id != 3 %>
            <td><%= link_to 'Show', unstructured_datum %></td>
            <td><%= link_to 'Edit', edit_unstructured_datum_path(unstructured_datum) %></td>
            <td><%= link_to 'Destroy', unstructured_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
        </tr>
        <% end %>
    </tbody>
</table>

<br>

<% if current_user.role.id != 3 %>
<%= link_to 'Input Data Tak Terstruktur Baru', new_unstructured_datum_path, class: 'btn btn-block btn-primary' %>
<% end %>

app/views/unstructured_data/new.html.erb
<h1>Input Data Tak Terstruktur Baru</h1>

<%= render 'form' %>

<%= link_to 'Kembali', unstructured_data_path %>

app/views/unstructured_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nama:</strong>
  <%= @unstructured_datum.name %>
</p>

<p>
  <strong>Subcriterium:</strong>
  <%= @unstructured_datum.subcriterium %>
</p>

<%= link_to 'Edit', edit_unstructured_datum_path(@unstructured_datum) %> |
<%= link_to 'Kembali', unstructured_data_path %>