config/routes.rb
Rails.application.routes.draw do

    devise_for :users
    scope "/admin" do
      resources :users
    end
  resources :roles

    root to: 'areas#index'

    get 'unstructured_data/ahp'
    post 'unstructured_data/ahpcalculate'
    resources :unstructured_data

    get 'ahp/criteria'
    post 'ahp/calculate'

    resources :criteria do
        resources :subcriteria
    end

    get  'plants/:id/detail' => 'plants#detail', as: :plant_detail
    post 'plants/:id/detail' => 'plants#savedetail', as: :plant_save_detail
    resources :plants

    get 'areas/:id/calculate' => 'areas#calculate', as: :area_calculate
    resources :areas

end

app/models/plant.rb
class Plant < ActiveRecord::Base
    has_many :plant_detail
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
    before_action :set_plant, only: [:show, :edit, :update, :destroy, :detail]
    before_action :set_detail, only: [:new, :edit, :create, :update]

    # GET /plants
    # GET /plants.json
    def index
        @plants = Plant.all
    end

    # GET /plants/1
    # GET /plants/1.json
    def show
    end

    # GET /plants/new
    def new
        @plant = Plant.new
    end

    # GET /plants/1/edit
    def edit
    end

    # POST /plants
    # POST /plants.json
    def create
        @plant = Plant.new(plant_params)

        respond_to do |format|
            if @plant.save
                # Jika pembuatan tanaman berhasil, buat juga parameter nya
                @details.each do |detail|
                    datadetail = PlantDetail.new
                    datadetail.area_id = @plant.id
                    datadetail.name    = detail[:name]
                    datadetail.detail  = params[:detail][0][detail[:name]]
                    datadetail.detail_type = detail[:tipe]
                    datadetail.detail_id   = detail[:id]
                    datadetail.save
                end
                format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
                format.json { render :show, status: :created, location: @plant }
            else
                format.html { render :new }
                format.json { render json: @plant.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /plants/1
    # PATCH/PUT /plants/1.json
    def update
        respond_to do |format|
            if @plant.update(plant_params)
                # Jika perubahan area berhasil, buat juga parameter nya
                @details.each do |detail|
                    cariDetail = PlantDetail.where(name: detail[:name], plant_id: @plant.id).first
                    if cariDetail != nil
                        datadetail = cariDetail
                    else
                        datadetail = PlantDetail.new
                    end
                    datadetail.plant_id = @plant.id.to_i
                    datadetail.name    = detail[:name]
                    datadetail.detail  = params[:detail][@plant.id.to_s][detail[:name]]
                    datadetail.detail_type = detail[:tipe]
                    datadetail.detail_id   = detail[:id]
                    datadetail.save
                end
                format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
                format.json { render :show, status: :ok, location: @plant }
            else
                format.html { render :edit }
                format.json { render json: @plant.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /plants/1
    # DELETE /plants/1.json
    def destroy
        @plant.destroy
        respond_to do |format|
            format.html { redirect_to plants_url, notice: 'Plant was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    def detail
        @details = []
        criteria = Criterium.includes(:subcriteria)
        #setiap looping sambil check ke database ada nilai ga
        criteria.each do |kriteria|
            if kriteria.subcriteria.length > 0
                sub = kriteria.subcriteria
                sub.each do |subkriteria|
                    @details.push({
                        tipe: 'subcriteria',
                        id: subkriteria.id,
                        name: subkriteria.name,
                        value: 0
                        })
                end
            else
                @details.push({tipe: 'criteria', id: kriteria.id, name: kriteria.name, value: 0})
            end
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
        @plant = Plant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_params
        params.require(:plant).permit(:name, :profile)
    end

    def set_detail
        @details = []
        criteria = Criterium.includes(:subcriteria)
        #setiap looping sambil check ke database ada nilai ga
        criteria.each do |kriteria|
            if kriteria.subcriteria.length > 0
                sub = kriteria.subcriteria
                sub.each do |subkriteria|
                    @details.push({
                        tipe: 'subcriteria',
                        id: subkriteria.id,
                        name: subkriteria.name
                        })
                end
            else
                @details.push({tipe: 'criteria', id: kriteria.id, name: kriteria.name})
            end
        end
    end
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/plants/_form.html.erb
<%= form_for(@plant) do |f| %>
  <% if @plant.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% @plant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, 'Nama Tanaman' %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <% @details.each do |detail| %>
  <div class="form-group">
      <label class="form-label"><%= detail[:name] %></label>
      <input type="text"
          class="form-control"
          name="detail[<%=@plant.id%>][<%=detail[:name]%>]"
          value="<%= (@plant.plant_detail.where(name: detail[:name]).first != nil) ?
                      @plant.plant_detail.where(name: detail[:name]).first.detail : 0  %>">
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/plants/detail.html.erb
<h3>Detail tanaman <%= @plant.name %></h3>
<hr>
<%= form_tag(plant_save_detail_path) do |f|  %>
    <% @details.each do |detail| %>
    <div class="form-group">
        <label><%= detail[:name] %></label>
        <input type="text"
            name="detail[<%=detail[:tipe]%>][<%=detail[:id]%>]"
            value="<%= detail[:value] %>"
            class="form-control" />
    </div>
    <% end %>
    <button class="btn btn-block btn-primary">Save</button>
<% end %>

app/views/plants/edit.html.erb
<h1>Edit Data Tanaman</h1>

<%= render 'form' %>

<%= link_to 'Lihat', @plant, class: 'btn btn-primary' %> |
<%= link_to 'Kembali', plants_path, class: 'btn btn-primary' %>

app/views/plants/index.html.erb
<% if notice %>
<p id="notice" class="alert alert-info"><%= notice %></p>
<% end %>

<h1>Daftar Tanaman</h1>

<table class="table table-bordered table-condensed table-striped">
  <thead>
    <tr>
      <th>Nama Tanaman</th>
      <th>Aksi</th>
    </tr>
  </thead>

  <tbody>
    <% @plants.each do |plant| %>
      <tr>
        <td><%= plant.name %></td>
        <td>
          <div class="btn-group">
            <%= link_to 'Lihat', plant, class: 'btn btn-mini btn-default' %>
            <%= link_to 'Edit', edit_plant_path(plant), class: 'btn btn-mini btn-default' %>
            <%= link_to 'Hapus', plant, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Input Tanaman Baru', new_plant_path, class: 'btn btn-mini btn-primary btn-block btn-raised' %>

app/views/plants/new.html.erb
<h1>Input Tanaman Baru</h1>

<%= render 'form' %>

<%= link_to 'Kembalis', plants_path, class: 'btn btn-block btn-primary' %>

app/views/plants/show.html.erb
<% if notice %>
<p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>
<p>
  <strong>Nama Tanaman:</strong>
  <%= @plant.name %>
</p>


<%= link_to 'Edit', edit_plant_path(@plant), class: 'btn btn-primary' %> |
<%= link_to 'Kembali', plants_path, class: 'btn btn-primary' %>