config/routes.rb
Rails.application.routes.draw do

    devise_for :users
    scope "/admin" do
      resources :users
    end
  resources :roles

    root to: 'areas#index'

    get 'unstructured_data/ahp'
    post 'unstructured_data/ahpcalculate'
    resources :unstructured_data

    get 'ahp/criteria'
    post 'ahp/calculate'

    resources :criteria do
        resources :subcriteria
    end

    get  'plants/:id/detail' => 'plants#detail', as: :plant_detail
    post 'plants/:id/detail' => 'plants#savedetail', as: :plant_save_detail
    resources :plants

    get 'areas/:id/calculate' => 'areas#calculate', as: :area_calculate
    resources :areas

end

app/models/area.rb
class Area < ActiveRecord::Base
    has_many :area_detail
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
    before_action :set_area, only: [:show, :edit, :update, :destroy]
    before_action :set_detail, only: [:new, :edit, :create, :update, :calculate]
    before_filter :authenticate_user!

    # GET /areas
    # GET /areas.json
    def index
        @areas = Area.all
    end

    # GET /areas/1
    # GET /areas/1.json
    def show
    end

    # GET /areas/new
    def new
        @area = Area.new
    end

    # GET /areas/1/edit
    def edit
    end

    # POST /areas
    # POST /areas.json
    def create
        @area = Area.new(area_params)
        respond_to do |format|
            if @area.save
                # Jika pembuatan area berhasil, buat juga parameter nya
                @details.each do |detail|
                    #if AreaDetail.where(name: detail[:name]) != nil
                    #end
                    datadetail = AreaDetail.new
                    datadetail.area_id = @area.id
                    datadetail.name    = detail[:name]
                    datadetail.detail  = params[:detail][0][detail[:name]]
                    datadetail.detail_type = detail[:tipe]
                    datadetail.detail_id   = detail[:id]
                    datadetail.save
                end
                format.html { redirect_to @area, notice: 'Area was successfully created.' }
                format.json { render :show, status: :created, location: @area }
            else
                format.html { render :new }
                format.json { render json: @area.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /areas/1
    # PATCH/PUT /areas/1.json
    def update
        respond_to do |format|
            if @area.update(area_params)
                # Jika perubahan area berhasil, buat juga parameter nya
                @details.each do |detail|
                    cariDetail = AreaDetail.where(name: detail[:name]).where(area_id: @area.id).first
                    if cariDetail != nil
                        datadetail = cariDetail
                    else
                        datadetail = AreaDetail.new
                    end
                    datadetail.area_id = @area.id.to_i
                    datadetail.name    = detail[:name]
                    datadetail.detail  = params[:detail][@area.id.to_s][detail[:name]]
                    datadetail.detail_type = detail[:tipe]
                    datadetail.detail_id   = detail[:id]
                    datadetail.save
                end
                format.html { redirect_to @area, notice: 'Area was successfully updated.' }
                format.json { render :show, status: :ok, location: @area }
            else
                format.html { render :edit }
                format.json { render json: @area.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /areas/1
    # DELETE /areas/1.json
    def destroy
        @area.destroy
        respond_to do |format|
            format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    # GET /areas/:id/calculate
    def calculate
        # ambil data area beserta detailnya
        @area = Area.includes(:area_detail).find(params[:id])
        # ambil data tanaman
        @plants = Plant.includes(:plant_detail).all
        # data criteria
        @criteria = Criterium.includes(:subcriteria)
        # definisikan gaps
        @gaps = []
        # definisikan variabel untuk score nanti
        @gapsScore = {}
        # ambil ahp untuk data unstructured
        @ahpUD = UnstructuredDatum.all
        @details.each do |detail|
            data           = {}
            data[:name]    = detail[:name]
            data[:plants]  = []
            data[:isRange] = false
            data[:isUnstructured] = (detail[:tipe]=='unstructured') ? true : false
            data[:ahplahan] = detail[:ahp]
            data[:tipe] = detail[:tipe]
            @plants.each do |plant|
                planttemp           = {}
                profile             = 0
                planttemp[:name]    = plant[:name]
                planttemp[:profile] = plant.plant_detail.where(name: detail[:name]).first.detail
                planttemp[:profilelahan] = @area.area_detail.where(name: detail[:name]).first.detail
                profile                  = planttemp[:profile].split("-")
                # jika nilai profile berupa range, tidak akan ada GAP
                if profile[1] != nil
                    data[:isRange] = true
                    # hitung interpolasinya dan dapatkan score
                    # rumus = f(x)=  {y2-y1} over {x2-x1} left (x-x1 right ) +y1
                    # x = profilelahan
                    rangeMin = profile[0].to_f
                    rangeMax = profile[1].to_f
                    planttemp[:score]   = countScore(rangeMin,rangeMax,planttemp[:profilelahan])
                else
                    if detail[:tipe] == 'unstructured' then
                        planttemp[:ahp] = @ahpUD.where("lower(name) = ?", planttemp[:profile].downcase).first[:ahp]
                        # planttemp[:gap] = planttemp[:ahp].to_f - data[:ahplahan].to_f
                        planttemp[:ahplahan] = @ahpUD.where("lower(name) = ?", planttemp[:profilelahan].downcase).first[:ahp]
                        planttemp[:gap] = planttemp[:ahplahan].to_f - planttemp[:ahp].to_f
                        planttemp[:score] = countScoreFromGapUD(planttemp[:gap])
                    else
                        # bukan unstructured
                        # hitung dulu gapnya
                        planttemp[:gap]   = planttemp[:profilelahan].to_f - planttemp[:profile].to_f
                        planttemp[:score] = countScoreFromGap(planttemp[:gap])
                    end
                end
                    if @gapsScore[plant.name] == nil
                        @gapsScore[plant.name] = {}
                    end
                    @gapsScore[plant.name][detail[:name]] = planttemp[:score]
#                 @gapsScore.push({name: plant.name, score: planttemp[:score], parameter: detail[:name]})
                data[:plants].push(planttemp)
            end
            @gaps.push(data);
        end
#         render json: @gaps and return
    end

    private
        def countScoreFromGapUD(gap)
            gap = gap.to_f
            # Buat tabel bobot gap
            i = 0
            gapsebelum = 0
            bobotsebelum = 0.00
            if gap > 0 then
                atas = 11.5
                angkaatas = 0
                (0..10).each do |n|
                    angkaatas = angkaatas + 10
                    atas = atas - 1.0
                    if ( gap > n && n < 1 ) then
                        return (( 11 - 10.5 )  / ( 0 - 10 ) * ( gap - 10 ) + 10.5 ).to_f
                    elsif gap > n && n > 0 then
                        return ((bobotsebelum.to_f - atas) / (n - gapsebelum.to_f) * (gap.to_f - gapsebelum.to_f) + atas).to_f
                    end
                    gapsebelum = angkaatas
                    bobotsebelum = atas
                end
            else
                # batas akhir
                atas = 12.0
                angkaatas = 10
                11.downto(1).each do |n|
                    if gap == 0 then return 11 end
                    angkaatas = angkaatas - 10
                    atas      = angkaatas - 1

                    if ( gap > angkaatas && n >= 10 ) then
                        # return gap
                        return (( 11.0 - 10.0 )  / ( 0.0 - (-10.0) ) * ( gap - (-10.0) ) + 10.0 ).to_f
                    elsif gap > angkaatas && n < 10 then
                        return ((bobotsebelum.to_f - atas) / (n - gapsebelum.to_f) * (gap.to_f - gapsebelum.to_f) + atas).to_f
                    end

                    gapsebelum   = angkaatas
                    bobotsebelum = atas
                end
            end
        end
        def countScoreFromGap(gap)
            gap = gap.to_f
            # Buat tabel bobot gap
            hasil = []
            atas  = 11
            angkaatas = 0
            (0..10).each do |n|
                if n == 0
                    hasil.push({
                        gap: 0,
                        bobot: 11
                    })
                else
                    angkaatas = angkaatas + 10
                    atas = atas - 1.0
                    hasil.push({ gap: -(angkaatas).to_f, bobot: atas})
                end
            end
            atas = 11.5
            angkaatas = 0
            (1..10).each do |n|
                if n == 0
                    hasil.push({
                        gap: 0,
                        bobot: 11
                    })
                else
                    angkaatas = angkaatas + 10
                    atas = atas - 1.0
                    hasil.push({ gap: (angkaatas).to_f, bobot: atas})
                end
            end
            bobot = 0
            hasil.each do |data|
                if data[:gap] == gap then
                    bobot = data[:bobot]
                    return bobot
                    break
                else
                    bobot = 0
                end
            end
                # udah selesai 1 looping dan belum dapet, berarti ga sama, pake interval, interpolasi
                sebelum = {}
                i=1
                hasil.each do |data|
                    if gap > 0
                        if data[:gap] > 0 && data[:gap].to_f > gap.to_f && i!=1 then
                            return data[:gap]
                            return "((#{sebelum.to_json} - #{data[:bobot].to_f}) / ( #{sebelum[:gap].to_f} - #{data[:gap].to_f} ) * ( #{gap} ) + #{data[:bobot].to_f} ).to_f"
                        else
#                             next
                            return data if i > 30
                        end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= form_for(@area) do |f| %>
  <% if @area.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% @area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, 'Nama Lahan' %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <% @details.each do |detail| %>
  <div class="form-group">
      <label class="form-label"><%= detail[:name] %></label>
      <input type="text"
          class="form-control"
          name="detail[<%=@area.id%>][<%=detail[:name]%>]"
          value="<%= (@area.area_detail.where(name: detail[:name]).first != nil) ?
                      @area.area_detail.where(name: detail[:name]).first.detail : 0  %>">
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/areas/calculate.erb
<h1>Proses Penilaian GAP / Perhitungan per Parameter</h1>
<% @gaps.each do |gap| %>
<h3><%=gap[:name]%></h3>
<div class="table-responsive">
    <table class="table table-condensed table-striped table-bordered">
        <thead>
            <tr>
                <th>Alternatif</th>
                <th>Profile Ideal</th>
                <th>Data Lahan</th>
                <% if gap[:isUnstructured] == false && gap[:isRange] == false %>
                    <th>Gap</th>
                <% end %>
                <% if gap[:isUnstructured] %>
                    <th>AHP Ideal</th>
                    <th>AHP Lahan</th>
                    <th>GAP</th>
                <% end %>
                <th>Score</th>
            </tr>
        </thead>
        <tbody>
            <% gap[:plants].each do |plant| %>
            <tr>
                <td><%=plant[:name]%></td>
                <td><%=plant[:profile]%></td>
                <td><%=plant[:profilelahan]%></td>
                <% if gap[:isUnstructured] == false && gap[:isRange] == false %>
                    <td><%=plant[:gap]%></td>
                <% end %>
                <% if gap[:isUnstructured] %>
                    <td><%=plant[:ahp]%></td>
                    <td><%=plant[:ahplahan]%></td>
                    <td><%=plant[:gap]%></td>
                <% end %>
                <td><%=plant[:score]%></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>
<hr>
<% end %>
<%
# siapin untuk hitung criteria
rangkings = {}
sum = {}
%>
<h2>Perhitungan Nilai Kriteria</h2>
<div class="table-responsive">
<% @criteria.each do |criterium| %>
<h3><%=criterium.name%></h3>
<table class="table table-condensed table-striped table-bordered">
<thead>
    <tr>
        <% if criterium.subcriteria.length <= 0 then %>
            <th>Parameter</th>
            <th>Nilai Kriteria</th>
        <% else %>
            <th>Parameter</th>
            <th>Bobot</th>
            <% @plants.each do |plant| %>
            <th><%=plant.name%></th>
            <% end %>
        <% end %>
    </tr>
</thead>
<tbody>
    <% if criterium.subcriteria.length > 0 then %>
        <% if sum[criterium.name] == nil then sum[criterium.name] = {} end %>
        <% criterium.subcriteria.each do |sub| %>
        <tr>
            <td><%=sub.name%></td>
            <td><%=sub.ahp%></td>
            <% @plants.each do |plant| %>
            <td><%=@gapsScore[plant.name][sub.name].to_f * sub.ahp.to_f%></td>
            <%
            nilai = 0.0
            nilai = @gapsScore[plant.name][sub.name].to_f * sub.ahp.to_f
            if rangkings[criterium.name] == nil then rangkings[criterium.name] = {} end
            rangkings[criterium.name][plant.name] = nilai
            if sum[criterium.name][plant.name] == nil then sum[criterium.name][plant.name] = 0.0 end
            sum[criterium.name][plant.name] = sum[criterium.name][plant.name] + nilai
            %>
            <% end %>
        </tr>
        <% end %>
        <tr>
            <td>NK</td>
            <td></td>
            <% @plants.each do |plant| %>
            <td><%=sum[criterium.name][plant.name]%></td>
            <% end %>
        </tr>
    <% else %>
        <% @plants.each do |plant| %>
        <tr>
            <td><%=plant.name%></td>
            <td><%=@gapsScore[plant.name]["Topografi"].to_f%></td>
        </tr>
        <% end %>
    <% end %>
</tbody>
</table>
<% end %>
</div>
</div>
<h2>Perhitungan Nilai Total dan Perangkingan</h2>
<div class="table-responsive">
    <table class="table table-bordered table-condensed table-striped">
        <thead>
            <tr>
                <th>Kriteria</th>
                <th>Bobot AHP</th>
                <% @plants.each do |plant| %>
                <th><%=plant.name%></th>
                <% end %>
            </tr>
        </thead>
        <tbody>
            <% sumrank = {} %>
            <% @criteria.each do |criterium| %>
            <tr>
                <td><%=criterium.name%></td>
                <td><%=criterium.ahp%></td>
                <% @plants.each do |plant| %>
                <%
                if sumrank[plant.name] == nil then sumrank[plant.name] = 0.0 end
                if sum[criterium.name] == nil
                    nilai = @gapsScore[plant.name]["Topografi"].to_f * criterium.ahp
                else
                    nilai = sum[criterium.name][plant.name] * criterium.ahp
                end
                sumrank[plant.name] = sumrank[plant.name] + nilai
                # sumrank[plant.name] = sumrank[plant.name] + sum[criterium.name][plant.name]
                %>
                <td><%=nilai%>
                <% end %>
            </tr>
            <% end %>
            <tr>
                <th colspan="2">Jumlah</th>
                <% rank = {} %>
                <% @plants.each do |plant| %>
                <% rank[plant.name] = sumrank[plant.name] %>
                <td><%=sumrank[plant.name]%></td>
                <% end %>
            </tr>
        </tbody>
    </table>
</div>
<h2>Rangking</h2>
<%rank = rank.sort_by {|_key, value| value}.reverse.to_h%>
    <%#=rank.to_json%>
<ul>
    <% rank.each do |k,v| %>
    <li><%="#{k}"%></li>
    <% end %>
</ul>

app/views/areas/edit.html.erb
<h1>Edit Data Lahan</h1>

<%= render 'form' %>

<%= link_to 'Lihat', @area, class: 'btn btn-primary' %> |
<%= link_to 'Kembali', areas_path, class: 'btn btn-primary' %>

app/views/areas/index.html.erb
<% if notice %>
<p id="notice" class="alert alert-info"><%= notice %></p>
<% end %>

<h1>Daftar Lahan</h1>

<table class="table table-condensed table-bordered table-striped">
  <thead>
    <tr>
      <th>Nama Lahan</th>
      <th>Aksi</th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.name %></td>
        <td>
          <div class="btn-group">
              <% if current_user.role.id ==3 %>
                <a href="<%=area_calculate_path(id: area.id)%>" class="btn btn-mini btn-primary">Cek Rekomendasi</a>
              <% else %>
            <%= link_to 'Lihat', area, class: 'btn btn-mini btn-primary' %>
            <%= link_to 'Edit', edit_area_path(area), class: 'btn btn-mini btn-primary' %>
            <%= link_to 'Hapus', area, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
              <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.role.id != 3 %>
<%= link_to 'Buat Lahan Baru', new_area_path, class: 'btn btn-primary btn-block' %>
<% end %>

app/views/areas/new.html.erb
<h1>Data Lahan Baru</h1>

<%= render 'form' %>

<%= link_to 'Kembali', areas_path, class: 'btn btn-primary' %>

app/views/areas/show.html.erb
<% if notice %>
<p id="notice" class="alert alert-info"><%= notice %></p>
<% end %>

<p>
  <strong>Nama Lahan:</strong>
  <%= @area.name %>
</p>

<%= link_to 'Edit', edit_area_path(@area), class: 'btn btn-mini btn-primary' %> |
<%= link_to 'Back', areas_path, class: 'btn btn-mini btn-primary'%>